# POMEN in VLOGE NEMŠKIH NAKLONSKIH ČLENKOV 

## Pomenoslovni in pragmatični pristop pri opisu pomena naklonskih členkov 

Pri opisu pomena naklonskih
členkov so glede na teoretično naravnanost in interesno ozadje možne velike
razlike.
Izsledke je le težko spraviti na skupni imenovalec, saj so ocene o
upravičenosti teh ali onih analiznih postopkov različne.
Weydt (1981:50d) ugotavlja,
da pri preučevanju členkov v bistvu prevladujeta dve raziskovalni smeri: ena
predvsem pomenoslovno (semantično) naravnana in druga predvsem pragmatično
naravnana smer.


### Pomenoslovni pristop

V okviru (pretežno)
pomenoslovnega (semantičnega) pristopa jezikoslovci poskušajo opisovati
naklonske členke natanko tako kot ostale slovarske enote.
V takem pristopu
nimajo samostojnega slovarskega (leksikalnega) pomena.
Slovarski pomen
predstavniki te smeri vidijo le v zvezi s pomenom povedi.
Le-tega implicira stavčni
naklon ('Satzmodus' ('Satzart')).

Med najvidnejšimi
predstavniki te smeri je **Krivnonosov**.

Krivonosov (1977:211) označuje naklonske členke kot izraz **logičnega silogizma**, tj.
kot znak, ki v besedilu kaže na
pomankljivost, nedovršenost sklepa in obvešča sogovornika o njih (prim. tudi
Krivonosov 1983 in Abraham 1991č).
Stavek, ki vsebuje naklonski členek, naj bi
bila sodba oz.
sklep glede govorne situacije, pri čemer ena izmed potrebnih
premis v jeziku ni izražena temveč implicirana (prim. tudi 3.4.5).
Pristop
Krivonosova sicer ni povsem semantično zasnovan.
Tudi Krivonosov mora svoje
strukturno analizno ogrodje 'napolniti' s pragmatično vsebino in uporabljati
interpretativne kategorije, saj izpeljuje odsotno premiso iz življenjskega
izkustva govorca in poslušalca (prim. tudi Krivonosov 1983:42).

Silogizem je vzročno posledični sklep na osnovi
prispevkov govorcev, ki ga sestavljata prvotni in drugotni stavek.
Prvotni
stavek vsebuje splošno, drugotni stavek pa posebno trditev.
Argumenti v
razpravi imajo svoj smisel le, če sta trditvi (premisi) resnični in udeležencem
besedilnega poteka znani.
Po Krivonosovu (1983:42) se v jeziku ne izraža
potrebna prva (splošnejša) trditev, ker je le-ta rezultat življenjskih izkušenj
govorca in poslušalca, izkušenj njunih predhodnih generacij in zato samoumevna.

Krivonosov (1977:208) ponazarja svoj pristop v (25) s stavkom *Ich bin doch ein ehrlicher Mensch, wozu soll
ich Sie denn belügen?*.
Premisa *Ehrliche
Menschen lügen nicht* je splošno (pri)znana.
Zgled (26) vsebuje popolno
obliko silogizma.

(25) 1. premisa: -
2. premisa: Ich bin doch ein ehrlicher Mensch.
sklep: Wozu soll ich Sie [denn]{.underline} belügen?

(26) 1. premisa: Ehrliche Menschen lügen nicht.
2. premisa: Ich bin ein ehrlicher Mensch.
sklep: Ich lüge nie.

Obstaja torej vsem udeležencem
znan razlog, zakaj vprašujoči ne laže.
Naklonski členek [denn]{.underline} nam kaže,
da ima govorec sobesedilno utemeljen razlog za vprašanje.

(419) Anna kommt aus den Steiner Alpen.
(A:
posebni primer)

 Leute
aus den Steiner Alpen können wie Bergziegen klettern.
(B: splošni primer)

 Anna
kann wie eine Bergziege klettern.
(C: sklep, posplošitev)

(420) Anna kann wie eine Bergziege klettern (C),
sie kommt ([ja]{.underline}) aus den Steiner Alpen (A).

V jeziku takih nepopolnih
(navideznih) silogizmov ne manjka, v nemščini pa dokaj pogosto nastopajo še
naklonski členki kot indeksikalni izrazi, ki kažejo, da v utemeljitvi nekaj
manjka (prim. tudi Krivonosov 1983 in Abraham 1991č).



Pristop Dohertyjeve temelji na
(kar se da) doslednem **ločevanju med stavčnim
in povednim pomenom** ('Satzbedeutung' nasproti 'Äußerungsbedeutung').

Dohertyjeva (1985) poskuša prvič v takšnem obsegu in v takšni doslednosti **opisovati stavčni pomen brez upoštevanja
povednega pomena**.
Po njej je pomembno ostro ločiti jezikovno in zunajjezikovno
določene deleže v interpretaciji naklonskih členkov - izhajati torej želi iz
samih lastnosti jezikovnih prvin, da bi lahko ustrezno opisala in razložila
njihove posebnosti.



Dohertyjeva (1985:15) pojmuje
naklonske členke (npr. [doch]{.underline}, [etwa]{.underline}, [denn]{.underline}, [ja]{.underline} in [wohl]{.underline}
) kot **pozicionalna** izrazna sredstva
(oz. **atitudinalna** - Doherty 1987), s
katerimi govorec izraža epistemski odnos (tj. naravnanost), ki se nanaša na
obstoj ali neobstoj dogodka v resničnosti ('Sachverhalt').
Povrhu z
naravnanostnimi členki ('Einstellungspartikel' - to je izraz, ki ga Dohertyjeva uporablja
namesto uveljavljenih izrazov 'Abtönungspartikel' in 'Modalpartikel') določamo
tudi odnos do drugih vrst naravnanosti (odnosov) nasproti temu dejstvu in
potemtakem tudi do drugih pozicionalnih sredstev.
Najpomembnejša je zato
sistemsko pogojena raba, ki jih zunajjezikovne danosti (sotvarja) ne morejo
izničiti ali obiti; pri tem ne gre za sistemsko pogojeno rabo samo ene vrste
jezikovnih izrazov, temveč celotnega sistema pozicionalnih izraznih sredstev.

Da bi pri opisu pomena posameznih naklonskih členkov lahko zajeli čim več
njihovih sobesedilnih lastnosti, je glede na povezanost z naklonskimi členki
potrebno oblikovati ustrezne sobesedilne razrede ('relevante Kontextklassen'),
ki določajo pogoje uporabe naklonskih členkov in potemtakem delujejo
omejevalno.
Dohertyjeva (1985:35) jih zato prav tako šteje k pozicionalnim
izraznim sredstvom.
Določeni stavčni prislovi, naklonski glagoli, stavčni
nakloni, stavčna nikalnica, po pomenu sorodna povedja in protivni poudarek
oblikujejo relevantne sobesedilne razrede, njihov pomen, nastopanje in
povezovanje pa opisuje s pomočjo pomenov naklonskih členkov.
Glede na svoje
osnovne domneve šteje Dohertyjeva je naravnanost del jezikovno določenega
stavčnega pomena, to pomeni, da so naravnanostne vrste predmet stavčnega
pomenoslovja (semantike) in ne pragmatike.
Po njenem prepričanju je le tako
mogoče spoznati invariantni osnovni pomen naklonskih členkov.



Dohertyjeva (1985 in 1987)
opisuje naklonske členke kot naravnanostna sredstva, kar je v očitnem nasprotju
z mnogimi drugimi jezikoslovci, ki obravnavajo in poudarjajo zlasti ilokutivne
značilnosti naklonskih členkov (npr. Helbig 1977, Bublitz 1978, Franck 1980,
Weydt/Hentschel 1983, Hentschel 1986).
Gre za navidezno nasprotje, saj tudi
Dohertyjeva meni, da so naklonski členki pomembni za ilokutivnost povedi (npr.
zmanjšujejo ilokutivno nejasnost povedi, saj kažejo, da je potrebno uporabljati
določeno védenje), vendar pa zagovarja stališče, da je ilokutivna relevantnost
naklonskih členkov osnovana na prepletanju epistemskega pomena različnih
izraznih sredstev in potemtakem pomenoslovna (tj. semantična).
Sobesedilne
omejitve pri uporabi naklonskih členkov kažejo mnoge drobne posebnosti
(idiosinkratičnosti), tako da jih najbrž ni mogoče posploševati (Doherty
1987:97).
Povzemam njene izsledke o 'naravnanostnih členkih' [ja]{.underline} in [denn]{.underline}.



**Naravnanostni členek [ja/JA]{.underline}**.
Nepoudarjeni [ja]{.underline} (27) je
vezan na trdilni naravnanostni naklon ('assertiver Einstellungsmodus')[[1]](#_ftn1),
njegov pomen pa lahko opišemo s stavčjem *'Možno
je, da poslušalec ve propozicijo (p)'* (Doherty 1987:101).
Poudarjeni [JA]{.underline}
je lahko protivni (kontrastni) [JA]{.underline} (28) ali namerni (intencionalni) [JA]{.underline}
(29); slednji je po Dohertyjevi (1987:131) le sobesedilna različica prvega.
Protivni
členek nakazuje (implicira) govorčevo/poslušalčevo védenje o propoziciji,
namerni členek pa nakazuje možnost, da poslušalec ve, da je nasprotna
propozicija (*-p*) s čustvenega
stališča ocenjena kot slaba.

(27) Konrad
ist [ja]{.underline} verreist.

(28) Konrad
ist [JA]{.underline} verreist.

(29) Komm [JA]{.underline} nach Hause!



**Naravnanostni členek [denn/DENN]{.underline}**.
Nepoudarjeni [denn]{.underline}
(31) je vezan na netrdilni oz.
odprti naravnanostni naklon, nakazuje pa oceno,
ki vprašanje omejuje na prvotno epistemsko vlogo (Doherty 1987:104).
Vprašanje
(30) lahko poslušalec razume (posredno) tudi kot poziv, medtem ko lahko razume
vprašanje (31) le kot vprašanje.
Dohertyjeva ne upošteva možnosti, da bi
vprašanje (31) lahko uporabili tudi kot retorično vprašanje (tj. kot posredno
izraženo trditev); to je še posebej jasno v zgledu (32).
Vprašljiv je najbrž
tudi pomenoslovni opis naklonskega členka, ki ga lahko povzamem s stavčjem *'govorec nakazuje, da poslušalec ve, ali je
naravnanostno ocenjena propozicija (p) ali nasprotna propozicija (-p) resnična'*.

Protivni členek [DENN]{.underline} (33) Dohertyjeva razlaga kot izpeljavo iz
nepoudarjenega členka [denn]{.underline} in protivnega poudarka, njegov pomen pa lahko
opišem s stavčjem *'govorec nakazuje, da
poslušalec ve, ali je naravnanostno ocenjena propozicija (p) ali nasprotna propozicija
(-p) ali alternativni del propozicije (npr. vprašalnica) resnič(e)n(a)'*.

Ena izmed sobesedilnih omejitev protivnega členka [DENN]{.underline} je njegova
nezdružljivost z neprozornimi stavčnimi prislovi (npr. [wahrscheinlich]{.underline}),
kar pa na sploh velja za odprti naravnanostni naklon, in celo s prozornimi
(npr. [wirklich]{.underline}).

(30) Kommst
du mit?

(31) Kommst
du [denn]{.underline} mit?

(32) Bist
du [denn]{.underline} wahnsinnig?

(33) Wo ist Konrad [DENN]{.underline} gewesen?



S pristopom Dohertyjeve (1985 in
1987) ali Wolskega (1986), ki izhaja s sorodnih teoretičnih stališč, ni mogoče
zajeti vseh plati uporabe naklonskih členkov.
Pri tako zelo sobesedilno
odvisnih izraznih sredstvih pa je pomenoslovno in pragmatično ravnino najbrž
potrebno ločiti.
Gre namreč za jezikoslovno razvojno obdobje, v katerem jezikovne
pojave, za katere se je zdelo, da jih je moč opisovati samo z
znotrajjezikovnimi pravili oz.
načeli, čedalje bolj 'osvajajo' teoretični
pristopi, ki so sobesedilno/sotvarno zasnovani, pragmatični in pogovorno
analitični.
Ločitev stavčnega in povednega pomena je Dohertyjeva izpeljala zelo
dosledno, kljub temu pa Bublitz (1988:242-243) meni, da dopolnjevanje njenih
pomenoslovno določenih rezultatov z interpretativnimi, sobesedilno vezanami
vidiki ni izključeno ali celo odvečno, temveč bi bilo celo zaželeno, saj je
trenutno še v zametkih (npr. v raziskavah Bastertove 1985 ali Hentschlove
1986).



Dohertyjeva (1982:175) želi
ločevati jezikovno določeni pomen od zunajjezikovno določenega pomena in se na
ta način izogniti napaki, ki jo po njenem mnenju pogosto delajo pragmatiki,
namreč da iz množice različnih povednih razredov (sobesedilnih razredov), v
katerih nastopa določen členek, izpeljujejo množico različnih pomenov členka
(Doherty 1982:174).
Tako naj bi na primer funkcija določene različice členka [doch]{.underline},
ki ima po mnenju pragmatikov (poenostavljeno) funkcijo »spominjanja na znano«,
ne izhajala iz določenega jezikovnega sredstva, temveč samo iz našega splošnega
izkustva, po katerem naj bi bile vsebine, o katerih govorimo, sogovorniku
ponavadi že znane (Doherty 1982:174).
Ta kritika je sicer upravičena in kaže
problematičnost nejasnega pragmatičnega pristopa, vendar pa Dohertyjeva sama
uporablja pojme, kot so 'pritrditev' ('Bekräftigung') in 'prepričevanje'
('Vergewisserung'), ki izvirajo iz pogovornega jezika in na katere krči pomen
členka [doch]{.underline}.



### Pragmatični pristop

Prvo delo, ki je bilo na
pragmatičnem področju nekakšen kažipot, je bila pogosto navajana **Weydtova disertacija (1969)**.
Izraz te
raziskovalne paradigme je npr.
tudi to, da so naklonske členke označevali kot
označevalce govornih dejanj, tj.
kot ilokutivne indikatorje (npr. Helbig
1977:34 ali Bublitz 1978:13), ali celo kot spreminjevalce govornih dejanj, tj.

kot modifikatorje ilokutivnih vlog (npr. Sandig 1979:89d; Franck 1980:108d).



V novejšem času so vidni napori,
da bi strogo ločevanje pomenoslovja (semantike) in pragmatike opustili.
To se
kaže zlasti v uporabi pojmov.
Medtem ko so 'pomen' rabili samo v pomenoslovnem
smislu, 'funkcijo' pa le v pragmatičnem smislu, je pojem 'pomen' prodrl tudi v pragmatični
tabor.
To je posledica položajske (statusne) spremembe raziskovalnih paradigm.

Ti jezikoslovci domnevajo, da naklonski členki nimajo pomena v tradicionalnem
smislu te besede.
**Pomen naklonskega
členka** razumejo predvsem **kot vsoto
pogojev za uporabo neke besede** (Wolski 1984:463) **oz. kot tisto, kar se - v zvezi z določenimi sobesedilnimi dejavniki -
stalno ponavlja** (Gornik-Gerhardt 1981:28).
Tistim jezikovnim prvinam, ki
sicer tudi služijo sporazumevanju, toda ne izmenjavi 'golih' informacij, potemtakem
tudi pripisujejo pomenoslovni položaj (semantični status).
Zato v takih delih
ne ločujejo jasno med pomenom in funkcijo.
Za te novejše pristope je tudi
značilno, da pri analizi v večji meri upoštevajo vlogo poslušalca.
Pogosto ti
jezikoslovci očitajo, da je tradicionalno pomenoslovje (semantika) vselej
zanemarjalo pomemben del besedišča, v katerega sodijo naklonski členki (prim.
Wolski 1984:458).



**Franckova** sodi pravi tako med tiste jezikoslovce, ki skušajo
ponatančiti pragmatični pristop, saj ga dopolnjuje s pomenoslovnimi
(semantičnimi) in slovničnimi (gramatičnimi) vidiki.
Po Franckovi (1980:216) so
pomenske sestavine naklonskih členkov tele:

1.
 Naklonski členki spremenijo govorno dejanje
('illokutionsmodifizierend').

2.
 Naklonski členki opredeljujejo sotvarje
('situationsdefinierend').

3.
 Naklonski členki krmilijo potek pogovora
('konversationssteuernd') in povezujejo sestavne dele pogovora med seboj
('konversationskonnektierend').

4.
 Naklonski členki so sredstvo za urejanje odnosov med
sogovorniki ('Beziehungsmanagement').

5.
 Naklonski členki so sredstvo za sprotno usklajevanje
interpretacije med pogovorom ('Interpretationsmanagement').

6.
 Naklonski členki relativirajo predikacijo (prisojevalni
sklad) in so argumentativni (utemeljujoči).

7.
 Naklonski členki so sestavni del določenih ritmičnih
vzorcev ('rhythmische Muster').

Pomen naklonskih členkov označuje
Franckova (1980:XII,167d,254d) kot navodilo za kontekstualiziranje
('Kontextualisierungsanweisung'), ki ga lahko izpeljemo z več ali manj konvencionaliziranimi
implikaturami.



Njen pristop je s stališča
konverzacijske teorije najobsežnejši.
Nanaša se na govorno situacijo (2.), na
govorca in poslušalca (4. in 5.), na jezikovno dejanje kot celoto (3. in 6.) in
na njegove dele (1. in 6.); poleg vidika dejanja ('Handlungsaspekt') obravnava
tudi tematsko vsebinski vidik.
Povrhu upošteva tudi ritmično zgradbo povedi.



Iz doslej navajanega je že jasno,
da moramo iskati pomen oz.
del pomena naklonskih členkov na nepropozicijskem
področju.
V naslednjih odstavkih bom opisoval njihov pomen in osvetlil različne
pristope v nekaterih doslej opravljenih raziskavah o naklonskih členkih.



Naklonski členki imajo različne
in kompleksne funkcije, ki so jih dognali šele v komunkikativno pragmatičnih
naravnanih disciplinah novejšega jezikoslovja (prim. tudi Helbig
1986:148d,234d).
Helbig (1988:56-63) navaja šest različnih funkcij naklonskih
členkov:

1.
 naklonski členki kot izrazi naravnanosti oz.
kot izrazi,
ki uravnavajo naravnanost ('Einstellungsausdrücke' oz. 'einstellungsregulierende
Ausdrücke');

2.
 naklonski členki kot izrazi, ki opredeljujejo sotvarje
('situations-definierende Ausdrücke');

3.
 naklonski členki kot izrazi, ki označujejo ali spremenijo
govorno dejanje ('illokutionsindizierend oder -modifizierend');

4.
 naklonski členki kot izrazi, ki krmilijo besedilni potek
('konversationssteuernde Ausdrücke');

5.
 naklonski členki kot izrazi z interakcijsko strateškimi
funkcijami ('Ausdrücke mit interaktionsstragischen Funktionen') in

6.
 naklonski členki kot vezniški izrazi ('konnektierende
Ausdrücke').



1.
 Weydt (1969:68) vidi pomen oz.
funkcijo naklonskih
členkov v tem, da izražajo **naravnanost
ali odnos govorca do izrečenega** ('die Stellung des Sprechers zum
Gesagten').
Z naklonskimi členki torej izraža govorec določene odnose,
predpostavke in pričakovanja, ki jih ima nasproti poslušalcu ob izvršitvi
dejanja.
V novejši jezikoslovni literaturi se, kot že povedano, v največji meri
strinjajo s tem, da naklonski členki ničesar ne prispevajo k vsebini propozicije,
temveč da so povezani z naravnanostjo govorca.
Sodijo torej predvsem na
intencijsko ravnino ali ravnino odnosov ('Intentionsebene') in ne na opisno
ravnino ('Darstellungsebene'), če se izrazimo z Weydtom (1969:61).
V tem smislu
je Dohertyjeva (1985) nekatere naklonske členke razumela kot slovarska izrazna
sredstva za različne načine naravnanosti in jih je zato imenovala kar **naravnanostni členki**
('Einstellungspartikeln').
V njeni jezikoslovni analizi imajo ti slovarski
izrazi jezikovni pomen, ki je osnova za to, da se s pomočjo sobesedila lahko
oblikuje ustrezen povedni pomen ('Äußerungsbedeutung') in z interakcijsko
situacijo ustrezen komunikativni smisel ('kommunikativer Sinn').
Wolski
(1986:383d,490) je izhajal iz podobnih teoretičnih izhodišč in je poskušal
teoretični pristop Dohertyjeve dopolnjevati.
Dokazoval je, da naklonski členki
ne izražajo kar sami različne načine naravnanosti (kot npr. ti. stavčni
prislovi - 'Satzadverbien' oz. naklonske besede - 'Modalwörter'), temveč da se
(statusno) uvrščajo nad načine naravnanosti, ki se izražajo z drugimi sredstvi
za različne vrste naravnanosti.
Wolski jih torej razume kot izrazna sredstva,
ki **uravnavajo** govorčevo naravnanost
ali odnos do pomenske podstave stavka ('einstellungs**regulierende** Ausdrucksmittel').



2.
 Naklonski členki vsebujejo tudi namige na percepcijo in
vrednotenje konkretnih in aktualnih govornih situacij, zlasti lastnosti, ki so
nastale s predhodno interakcijo (prim. Franck 1980:31d); Kemme 1979:27) - zato
so tudi izrazi, ki **opredeljujejo
sotvarje** ('situations-definierend').
Zaradi tesne zveze med naklonskimi
členki, sobesedilom in sotvarjem jih nekateri raziskovalci primerjajo tudi z
deiktičnimi izrazi, saj v sporočanje prav tako vnašajo prvine govorne situacije
(prim. Franck 1980:25; Hentschel 1986:14dd; Thurmair 1989).
Po Hentschlovi
(1986:122) nevarnost zanemarjanja sobesedila zmanjšujejo naklonski členki kar
sami.
Kot metakomunikativne deiktične besede kažejo na komunikativno sobesedilo
povedi in jamčijo, da sobesedila ne zanemarjamo.
Stavki, v katerih nastopajo
naklonski členki, zato vselej vsebujejo tudi informacije o sobesedilu, ki ga na
ta način zlahka izluščimo.



3.
 Naklonski členki se nanašajo na **govorna dejanja ('Sprechhandlungen')**, kar se kaže v omejitvah glede
nastopanja v različnih stavčnih naklonih.
Zato so tudi izrazi, ki **nakazujejo ali spremenijo ilokucijo**
('illokutionsindizierend oder -modifizierend'; prim. tudi König 1977:117; Weydt
1977:225 ali Franck 1980:21).
To funkcijo naklonskih členkov kot **ilokutivnih označevalcev (indikatorjev)**
so razkrili predvsem v okviru teorije govornih dejanj (npr. Wunderlich
1972:18d; Helbig 1977; Helbig/Kötz 1981:15d).
Naklonski členki sodijo k
ilokutivnim indikatorjem, tj.
k tistim jezikovnim sredstvom, ki osmislijo poved
razmeroma neodvisno od sobesedila, v katerem se govorno dejanje opravi
('Handlungskontext').

(405) Du
kannst [mal]{.underline} das Fenster schließen.

(406) Du
kannst [ja]{.underline} das Fenster schließen.

(407) Du kannst [doch]{.underline} das Fenster
schließen.

Govorec v (405) izreka
neobvezujoč poziv, v (406) nasvet in v (407) nasvet ali soglasje k želji
sogovornika.
Pojmovanje o naklonskih členkih kot o ilokutivnih indikatorjih so
v kasnejših delih ponatančili in relativizirali.
Helbig (1988:59) domneva, da
je možno izhajati iz tega, da so nekateri naklonski členki (kot npr. [etwa]{.underline}
ali [denn]{.underline} za vprašanja) že po svoji porazdelitvi specifični za določene
tipe govornih dejanj (saj res nakazujejo govorno dejanje); da imajo drugi
naklonski členki nespecifično porazdelitev in se zato pojavljajo v različnih tipih
govornih dejanj (npr. [doch]{.underline}, [eben]{.underline}, [eigentlich]{.underline}); in da imajo
nekateri naklonski členki (npr. [bloß]{.underline}, [mal]{.underline}, [schon]{.underline}) še manj
specifično porazdelitev.
Tako je pri indikaciji govornega dejanja možno
domnevati različne stopnje (prim. tudi Hartmann 1977:104; Hinrichs 1983:275d).



4.
 Če izhajamo iz tega, da delujejo naklonski členki na
ravnini odnosov ('Beziehungsebene'; nasprotje: opisna ravnina, tj.
'Darstellungsebene'), torej med sogovornikoma, in da so predvsem interakcijske
prvine (prvine součinkovanja), je potrebno vplesti tudi vidik sogovornika in
sobesedila, ki se bežno kaže tudi že pri Weydtu (1969:22,62).
Jasneje se
orientacija k poslušalcu odraža pri (Bublitzu 1978:38), ki govori o **navodilih za razumevanje izrečenega**
('Verstehensanweisungen'), in pri Gornik-Gerhardtovi (1981:18), ki naklonske
členke razume kot **inštrukcije
poslušalcu, kako naj razume propozicijo**.[[2]](#_ftn2)
Podobno meni Thurmairjeva (1989:94), da lahko govorec z naklonskimi členki
sogovorniku namigne, kako naj izrečeno razume in v kateri 'predal' naj le-to
vloži, kako govorec vrednoti poved, kako je razumel predhodno poved ali kako
ocenjuje védenje in pričakovanja poslušalca.
Te namige naj poslušalec upošteva
v svojem odzivu.
Po Thurmairjevi je zato tudi možno reči, da je ena izmed
funkcij naklonskih členkov, da v določenem pogledu vpliva na sogovornika.
Z
naklonskimi členki lahko kažemo na različne vidike govorne situacije (prim.
tudi König 1977:117; Burkhardt 1982c:153): z njimi lahko kažemo na predhodno
informacijo, na zvezo s predhodnimi prispevki govorcev, lahko podamo neopazen
'meta-komentar' o predhodnem govornem prispevku in lahko vplivamo na pripravo
novih govornih prispevkov.
Glede na konverzacijski vidik indicirajo naklonski
členki položaj med pogovorom (kažejo, ali je sogovornik na začetku, v sredini
ali na koncu pogovora) in so izrazi, ki **krmilijo
konverzacijo (pogovor)**, saj vplivajo na nadaljnji potek pogovora (prim.
Franck 1980:31d; Baunebjerg/Wesemann:1983:121d).



5.
 Naklonski členki imajo tudi **interakcijsko strateške funkcije**, saj uvrščajo posamezno poved v
interakcijski okvir, npr.
s povezavo s predhodnimi ali sledečimi dejanji (prim.
König 1977:129).
V danih razmerah interakcije z ustreznimi jezikovnimi sredstvi
razjasnjujejo funkcijo govornega dejanja.
So izrazi za nepopolne načine dejanj
('Handlungsarten'), s katerimi lahko govorec tudi govorna dejanja, ki jih je
moč osamiti, izrecno navezuje na interakcijske razmere (prim. Sandig 1979:89d).

Naklonski členki izražajo tudi domneve, vrednotenje, pričakovanje glede na
odziv sogovornika, glede na odgovor - npr.
je nekaj naklonskih členkov v
odločevalnih vprašanjih (npr. [etwa]{.underline}, [nicht]{.underline}, [doch]{.underline}), ki imajo
to bistveno funkcijo, da v tovrstnih 'tendencioznih' vprašanjih izražajo
preferenco za pozitiven ([nicht]{.underline}, [doch]{.underline}) ali za negativen odgovor ([etwa]{.underline})
(prim. Franck 1979:3d).
S to okolnostjo so povezane govorčeve domneve o
sogovorniku.
Te domneve pojasnjujejo, katere predstave ima govorec glede
sogovornikovega védenja, njegove naravnanosti itd.).
Ena izmed interakcijskih
funkcij je ta, da slabijo ali krepijo propozicijo ali da jo vnesejo v določen
interakcijski okvir (prim. Franck 1980:31d,117).
Pri poslušalcu povzročajo
odzive, ki jih v isti povedi brez naklonskega členka ne bi bilo (prim. tudi
Bastert 1985:6).
Iz značilnosti, da se naklonski členki nanašajo na interakcijo
v dialogu, po Thurmairjevi (1989:97) sledi, da je ustrezen opis njihovega
pomena možen le na jezikovni ravnini, ki je višja od stavka.
Naklonski členki
nosijo v sebi informacije o možnih sobesedilih kot nekakšni 'radikali', ki
potrebujejo za svojo zašicenost določene 'spojine'.
Moja trditev, da je stavek
(poved) z naklonskim členkom pomensko ožji kot stavek (poved) brez naklonskega
členka, temelji prav na tem.
Število možnih sobesedil, v katerih lahko nastopa
stavek (poved) z naklonskim členkom, je potemtakem manjše kot število
sobesedil, v katerih lahko nastopa stavek (poved) brez naklonskega členka.



6.
 Mnogi naklonski členki imajo tudi **povezovalno funkcijo** ('konnektierende Funktion'), saj povezujejo
zaporedno nastopajoče povedi tudi tedaj, ko postane govorec poslušalec,
povezujejo vsebino stavka, v katerem je naklonski členek, na logičen način z
vsebino, ki je bila predhodno izrečena, ali z vsebino, ki sploh ni bila
izrečena, ampak je rezultat zaznavanja, predhodnega védenja ali mišljenja
(prim. Franck 1980:31d; Kemme 1979:15d,27,67d).
Funkcijo povezovanja besedila
('textverknüpfende Funktion') delijo naklonski členki z vezniki.
Zato je
marsikdaj možna parafraza (prim. Kemme 1979:27d; Schulz 1973):

(411) Ich
gehe nicht schwimmen, [weil]{.underline} das Wasser noch viel zu kalt ist.

(412) Ich
gehe nicht schwimmen, das Wasser ist [ja]{.underline} noch viel zu kalt.

(413) Ihr
sollt das Obst nicht essen, [weil]{.underline} es noch nicht gewaschen ist.

(414) Ihr sollt das Obst nicht essen, es ist [doch]{.underline}
noch nicht gewaschen.

Zaradi podobnosti z vezniki so te
naklonske členke imenovali tudi 'povezovalne členke' (Becker 1976:6d).
Vendar
vezniki vedno povezujejo eksplicitno izražene povedi, medtem ko naklonski
členki ne vselej, kajti pogosto povezujejo povedi z odnosi, domnevami idr., ki
niso eksplicitno izraženi.
Poleg tega pomena naklonskega členka ne smemo zoževati
zgolj na povezovanje besedilnih zgradb.
Ta funkcija je povezana s
konverzacijsko, interakcijsko in ilokutivno funkcijo, saj je treba besedila na
sploh vložiti v te temeljujoče kontekste in jih razložiti iz njih.



**Dialog in monolog.**
Zaradi tesne zveze med naklonskimi členki, sobesedilom in sotvarjem mnogi
slovničarji menijo, da lahko pomen naklonskih členkov opisujemo le v dialoškem
okviru.
Glede na to, da se naklonski členki pojavljajo tudi v monoloških
besedelih, je mnenje teh raziskovalcev o dialogu kot edini relevantni besedilni
vrsti pretirano.
Utemeljena se zdi domneva o dialogu kot prvotnejši obliki
jezikovne rabe, o monologu kot ontološko drugotnejši obliki jezikovne rabe.
Res
je tudi, da se naklonski členki pogosteje pojavljajo prav v dialoških
besedilih.
Oboje utegne imeti posledice za delovno domnevo o naklonskih členkih
kot krepitvenih stavčnih prvinah.



## Funkcijske različice ali skupno pomensko jedro 

Helbig (1988:67d) piše, da doslej
teoretično ni povsem jasno, ali so posamezni členki le različne **funkcijske različice** (npr. [doch]{.underline}~1~,
[doch]{.underline}~2~, [doch]{.underline}~3~ itd.) ali pa je različnim
funkcijskim različicam možno pripisovati **skupno
pomensko jedro** ('Gesamtbedeutung' ali 'Grundbedeutung'), ki bi ga bilo
mogoče opredeliti po metodah semantike.



Ta težava ima
znanstvenozgodovinske korenine.
V **prvi
fazi** so slovničarji večinoma menili, da so naklonski členki besede z revnim
pomenom ali celo brez njega ('bedeutungsarm' ali 'bedeutungsleer').
V slovnicah
in slovarjih so jih nezadostno opisovali, pogosto pa so jih s slogovnega vidika
celo označevali kot mašila ali polnila in njihovo rabo odsvetovali.
V **drugi fazi**, ko se je v jezikoslovju
uveljavljala komunikativno-pragmatična raziskovalna paradigma, so členkom
pripisovali precej večji pomen.
Najzanimivejša je bila komunikativna vrednost
členkov, pri čemer so prevladovale predvsem pragmatične razlage njihovih
funkcij.
Šele v zadnjih letih - v nekakšni **tretji
fazi** - se jezikoslovci intenzivneje ukvarjajo z invariantnimi skupnimi
pomenskimi obeležji, ki naj bi bila osnova za različne rabe in funkcije v
različnih sobesedilih in sotvarjih.



Soodvisnost naklonskih členkov in
sobesedila je jezikoslovce pogosto pripeljala do vprašanja, koliko pomenov naj
bi imel naklonski členek.
Krivonosov (1963/77:44) ugotavlja, da se pomen
naklonskega členka spreminja od stavka do stavka, izhajal pa je iz tega, da
naklonski členek svoj pomen dobi le skupaj s stavkom.
Krivonosov (1977:193)
piše, da ima isti naklonski členek v različnih stavčnih tipih manj skupnega kot
različni naklonski členki v istem stavčnem tipu.
To pojmovanje je v nasprotju z
možnostmi ali omejitvami kopičenja naklonskih členkov.
Še jasneje se to
prepričanje kaže pri Helbigu (1977:400), ki pravi, da bi moral podroben opis
naklonskih členkov specificirati posamezne slovarske enote po svojih pomenih
(npr. [auch]{.underline}~1~, [auch]{.underline}~2~, [auch]{.underline}~3~,
[auch]{.underline}~4~, [auch]{.underline}~5~).
Dejansko se najde v
didaktičnem delu Helbig/Kötz (1981) pet slovarskih enot [auch]{.underline} in sedem
slovarskih enot [doch]{.underline}.
Zveze med posameznimi funkcijami pogosto ni moč
videti (prim. podobno tudi Heinrichs 1981:120,196).
Tako stališče je v
jezikoslovju znano kot **pomensko
maksimalistično stališče** ('bedeutungsmaximalistische Position').



**Maksimalistično** stališče ima več **slabosti** (Thurmair 1989:98):

- Dokaj
neverjetno je, da bi vsak govorec shranjeval več (deloma do šest) različic
posameznega naklonskega členka, poleg teh pa še ostale funkcije členka (prim.
tudi Hentschel 1986:121).

- Maksimalistično
stališče je še problematičnejše za poslušalca, saj le-ta ne bi imel na voljo
znamenj o tem, katero različico naklonskega členka je imel govorec v mislih, če
se te različice ne bi ločevale ne po naglasu, ne po poudarku in ne po
porazdelitvi v različnih stavčnih naklonih.

- Tudi
v praksi, npr.
med poukom nemščine kot tujega jezika, so rezultati na osnovi
maksimalističnega stališča dokaj neuporabni.



Glede na poplavo posamičnih
raziskav o naklonskih členkih je Weydt že pred leti svaril pred tem, da lahko
raziskovalci izgubijo nekakšno 'zdravo' mero pri razlikovanju pomenskih
različic naklonskih členkov in razlikujejo čedalje drobnejše pomenske razlike,
pri tem pa ne bi upoštevali, da členki v samem jeziku tvorijo celoto (Weydt
1977:222d).
Weydt/Hentschel (1983:4) sta govorila o tako imenovanem **členkovnem paradoksu**
('Partikelparadoxon'): obstaja nevarnost, da oblikujemo vseobsegajoč pomen
('übergreifende Bedeutung') naklonskih členkov presplošno, opis pomenskih
različic pa pretirano podrobno (prespecifično).



V raziskavah o naklonskih členkih
so pri opredeljevanju pomena naklonskih členkov izhajali iz različnih gledišč
(Bastert 1985:45):

- Eni
so domnevali, da obstaja nekakšen **osnovni
pomen** ('Grundbedeutung'), na osnovi katerega je možno opisovati vse
pomenske različice.
Kemme (1979:13d) npr.
domneva, da je za pomen naklonskih
členkov treba predpostaviti pomen njihovih istoglasnic (homografov).

- Drugi
so poskušali opredeliti pomen naklonskih členkov kot **povzetek posamičnih pomenskih analiz** ('Zusammenfassung aus
Einzelanalysen').



Po Helbigu (1988:68d) so se
jezikoslovci lotevali vprašanja **skupnega
pomena** ('Gesamtbedeutung') na različne načine: npr.
Lüttnova (1977) v
glavnem tako, da ni upoštevala posameznih situacijsko specifičnih členkovnih
rab, Weydt (1977:220) predvsem na osnovi členkovnih rab, ki kot istoglasnice
izzivajo vprašanje enotnosti členka.
Tako so npr.
opazili (prim. npr. Kemme
1979:13d), da imajo različne rabe členka [ja]{.underline} skupno obeležje pritrditve,
različne rabe členka [doch]{.underline} skupno obeležje nasprotja, različne rabe
členka [denn]{.underline} skupno obeležje pojasnitve, različne rabe členka [auch]{.underline}
in [nur]{.underline} skupno obeležje pridružitve k neki množici oz.
omejitve na neko
množico itd.
Ti poskusi so bili še nezadovoljivi, saj se je zdelo, da osnovni
ali skupni pomeni členkov manj razjasnjujejo kot sobesedila in sotvarja.
Zato
so se nekateri slovničarji usmerili bolj na govorne situacije (govorne
položaje), ker so menili, da naklonski členek v posamezno interakcijo prispeva
le pomenski potencial, ki se razvije šele v govorni situaciji (prim. Kirstein
1983:213d,222d).
Na ta način so ti avtorji naklonskim členkom pogosto
pripisovali obeležja sobesedila, ker niso zadostno razlikovali med pomenskim
deležem, ki ga prispeva sam naklonski členek, in pomenskim deležem, ki ga
prispeva sobesedilo.
Nasprotno je Dohertyjeva (1985:7,12d) poskušala
dokazovati, da členki (vsaj nekateri naklonski oz. naravnanostni členki)
razpolagajo s po enim invariantnim (nespremenljivim) pomenom, ki je osnova
sobesedilno pogojenim različicam in ki ga potemtakem tudi situativno sobesedilo
ne more izničiti (nevtralizirati).



Pristop Dohertyjeve (1985), ki je
značilen in nekakšen kažipot v tretji fazi raziskav o nemških členkih, je
zaznamovan z jasnim dvomom nasproti teoretičnim pristopom, ki razlagajo členke
izključno na komunikativni osnovi in na osnovi govornih dejanj.
Zanjo je
značilno, da poskuša vse komunikativne in ilokutivne možnosti členkov dojeti
kot posledico slovarskega (znotrajjezikovnega) pomena.
Dohertyjeva (1985) je
posegla po Bierwischovem (1979 in 1983) razlikovanju med stavčnim pomenom
('Satzbedeutung'), povednim pomenom ('Äußerungsbedeutung') v sobesedilu in
komunikativnim smislom ('kommunikativer Sinn') v interakciji; s tem je povezana
tudi njena predpostavka, da povednega pomena in komunikativnega smisla ni
mogoče razumeti kot nekaj, kar je neodvisno od jezikovnega pomena, pač pa kot
nekaj, kar je načelno vezano nanj.
To predpostavko je Wolski
(1986:354d,357d,360d,445d,481) prenesel na naklonske členke in poskušal njihove
pragmatične funkcije razložiti iz dobesednega (slovarskega) pomena in ne iz
sobesedila in sotvarja.
Pogoste prvine dosedanjega jezikoslovnega besedišča v
okviru komunikativno pragmatične znanosti zato opušča, ker ne kažejo na pomen
temveč na komunikativni smisel.
Na ta način preprečuje tudi atomizacijo
členkovnega pomena na številne funkcijske različice.
Namesto tega ustvarja
model, v katerem se te različne analizne ravnine nanašajo ena na drugo in v
katerem je v ospredju vprašanje generičnega pomena posameznega členka in **pomensko minimalistično stališče**.

Rekonstrukcijo splošnega pomena sicer zahtevo analizo tipov členkovne rabe (v
posameznih stavčnih tipih z nastopajočimi omejitvami vred), toda ta pomen po
drugi strani utemeljuje posamezne tipe členkovne rabe in se zato razvije glede
na posamezne stavčne tipe (kritika takega znotrajjezikovnega abstraktnega
pomena npr. v delu Bastertove 1985:6).



**Slabosti minimalističnega** stališča se kažeta v tem, da je 1.
težko
izluščiti tako abstraktno skupno pomensko jedro in da v marsikaterem primeru še
ni uspelo ter da je 2.
ta invariantni pomen tako splošen in abstrakten, da za
leksikografske namene ni zadosten.
Prej dognane sobesedilne različice s svojimi
funkcijami torej niso odvečne.
'Členkovni paradoks' (Weydt/Hentschel 1983:3d)
se kaže v zahtevi po semantičnem opisu medsebojne zveze med funkcijskimi
različicami (tj. po vseobsegajočem pomenu) in hkratni zahtevi po preprostosti
in razumljivosti.
Pomenska jedra, ki so skupna posameznim različicam, so tako
abstraktna, da povprečnemu uporabniku ne pomagajo veliko, opis posameznih
funkcijskih različic pa onemogoča, da bi uporabnik razumel povezave med
posameznimi različicami.



Po Abrahamu/Wuitu (1984:156; po
Helbigu 1988:70) je neizbežno, da opisujemo tako posamezne funkcijske različice
kot tudi skupni pomen členkov, ne da bi pri tem pozabili, da so skupni pomeni
nujna, toda hkrati tudi še nerešena raziskovalna naloga (prim.
Weydt/Harden/Hentschel/Rösler 1983:159), da so neobhodno splošni, da je z
njihovo pomočjo težko na razumljiv način razložiti posamezne različice, da je
konec koncev potrebno prenesti jezikoslovno dognan pomen te vrste v
leksikografska besedila (ki so pač mišljena za jezikoslovno neizobražene
bralce) in da zato tudi ne morejo biti zgolj redukcija jezikoslovnih analiz
(prim. Wolski 1986:449dd).
Te težave glede skupnega pomena se nanašajo tako na
generični pomen (po zamisli Wolskega), ki je omejen na členke, kot tudi na
vseobsegajoči pomen ('übergreifende Bedeutung' - po Weydtovem pojmovanju), ki
zaobsega tudi istoglasne besede kot npr.
veznike ali prislove in lahko vodi do
izgube ali omalovaževanja razlik med besednimi vrstami (prim. Wolski
1986:388dd).



Kljub problemom, ki se v tej
zvezi pojavljajo, se v novejšem jezikoslovju večina jezikoslovcev zavzema za
pomensko minimalistično stališče ('bedeutungsminimalistische Position'), tj.
da
domnevamo samo en skupni pomen posameznega naklonskega členka (prim. npr. König
1977, Bublitz 1978, Weydt/Hentschel 1983, Doherty 1985 in 1987, Wolski 1986,
Hentschel 1986, Thurmair 1989).
Srednjo pot med obema stališčema je ubrala
Franckova (1980:175), ki sicer razlikuje funkcijske različice naklonskih
členkov (npr. šest različic naklonskega členka [doch]{.underline}), vendar jih
večinoma opisuje kot različice 'standardnega primera' (npr. pet izmed šestih
različic naklonskega členka [doch]{.underline}) in tako pokaže, da pomenske različice
naklonskih členkov lahko opisujemo kot konvencionalizirane implikature in da
jih lahko izpeljemo iz ustreznih ilokutivnih in sobesedilnih lastnosti.



V svoji raziskavi sem se odločil
izhajati iz domneve, da ima posamezen naklonski členek samo en pomen.
Sicer je
možno, da se pomen naklonskega členka, ki lahko nastopa v različnih stavčnih
naklonih, 'premakne'.
Po Thurmairjevi (1989:98d) pa bi tak pomenski premik
lahko spoznal tudi poslušalec, saj le-ta razlikuje stavčne naklone med seboj
(npr. vprašanje od poziva), zato lahko razlikuje morebitne spremembe v pomenu
naklonskega členka glede na stavčni naklon.
Načelno bom torej domneval samo en
skupni pomen sobesedilnih različic naklonskega členka, ki je lahko glede na
stavčni naklon bolj ali manj izoblikovan (prim. tudi Dittmann 1982:199: MP als
'Familie von Fällen' - po Bastertovi 1985:45).
Značilna soodvisnost med
naklonskimi členki in sobesedilom ni zagotovilo za pravilnost domneve, da se z
vsako spremembo sobesedila spremeni tudi pomen naklonskega členka.
Obstajati
mora možnost, da z analizo vseh različnih sobesedil, v katerih lahko nastopa
posamezni naklonski členek, določamo sobesedilno neodvisen pomen naklonskega
členka (Thurmair 1989:99; prim. tudi Franck 1980:167).



**Pomen** lahko razumemo kot semantični pojem.
Poglejmo členek [doch]{.underline}
v povedih (403) in (404).
Členku [doch]{.underline} pripisujemo tale osnovni pomen: a)
anaforičnost, b) nasprotnost.
To je skupni pomen obeh členkovnih rab v (403) in
(404), ki je v tem primeru enak osnovnemu.
Sobesedilni pomen naklonskega členka
v povedi (404) pa vsebuje obeležja, ki jih veznik v povedi (403) nima: gre za
obeležje trdilnosti, tj.
vezanosti na trdilno govorno dejanje.
Poleg tega je
lahko obeležje nasprotnosti v sobesedilu neizraženo, kar pomeni, da z
naklonskim členkom nanj le namigujemo (impliciramo).

(403) Das
dort ist Marias Mutter, [doch]{.underline} diese Frau hier ist Peters *Mutter*.

(404) Vorsicht ist [doch]{.underline} die *Mutter* der Porzellankiste.

**Komunikativna funkcija** je pragmatični pojem in jo lahko opredelimo
kot vlogo jezikovnega izraza v sobesedilu in/ali sotvarju.
Za razliko od pomena
jezikovnega izraza je funkcija jezikovnega izraza relacionalen pojem.
Pojem
funkcije uporabljamo sicer tudi v skladnji.
Skladenjska vloga izraza [Mutter]{.underline}
je v obeh povedih ista, tj.
jedro povedkovega določila.
Komunikativna funkcija
ali pragmatična vloga izraza [Mutter]{.underline} v gornjih povedih je različna: v
(403) je morebitna ali dejanska udeleženka v besedilnem svetu, v (404) pa to ni.

Skladenjska funkcija izraza [doch]{.underline} v (403) je veznik, v (404) pa naklonski
členek.
Ena izmed pragmatičnih, tj.
komunikativnih vlog naklonskega členka je
spominjanje na znano vsebino, ki je v nasprotju z nakazano (implicirano).
Te
pragmatične funkcije veznik nima.
Pragmatično vlogo lahko pogosto izpeljemo iz
osnovnega oz.
sobesedilnega pomena členka (prim. tudi možno izpeljavo
pragmatičnega pomena pomanjševalnic iz osnovnega pomena pomanjševalnic).



Pojem **implikature** se uporablja skladno z Griceovim pojmovanjem (1979).

Vključene (implicirane), vendar neizrečene stavke lahko poslušalec razume le
takrat, če se njegovi miselni procesi usmerjajo skladno z določenimi
pogovornimi pravili in dogovori v jezikovni skupnosti.
Gre za splošno načelo
sodelovanja (kooperativno načelo) in njemu podrejene štiri posebne pogovorne
maksime (maksime količine, kakovosti, bistvenosti in načina).
Pogovorna pravila
morajo udeleženci besedilnega poteka uporabiti s svojim splošnim védenjem
(enciklopedičnim védenjem), ki je dostopno s pomočjo sklepanja.
Poleg
konvencialnega, dobesednega pomena razlikuje Grice (1979) **tri vrste implikatur**, tj.
**konvencionalno**,
**splošno pogovorno** in **posebno pogovorno** implikaturo.

Implikature, če gre za konvencionalne ali situacijsko specifične implikature,
je možno razbrati iz védenja pogovornih maksim.
Povrhu mora biti zagotovljeno,
da sogovornika pričakujeta drug od drugega razumno (racionalno) dejanje (prim.
Franck 1980:11).
Grice (1979) domneva, da so pogovorna pravila drugačna kot
slovnična, češ da jih lahko prekršimo; poved ostane kljub temu smiselna,
sprejemljiva in slovnično pravilna.
Po njegovem mnenju je nadrejeno načelo
sodelovanja ponavadi tako močno, da tudi potem, ko je govorec prekršil
pogovorno maksimo, poslušalec poskuša najti možno interpretacijo, kot da
prekršek ne bi bil opazen, in ki bi izhajala iz dodatnega, neizraženega pomena
(prim. tudi Hörmann 1976 in Leiss 1992: 'Prinzip der Sinnkonstanz' - načelo
konstantnosti smisla).
Neoptimalna uporaba povedi povzroča implikaturo, tj.

reinterpretacijo pomena po načelu sodelovanja oz.
po načelu konstantnosti
komunikativnega smisla.


-----------------------------------------------------------------------

[1] Pomenoslovni
pojem 'Einstellungsmodus' pribli\`no ustreza Altmannovemu (1987) pojmu
'Satzmodus' (stav\~ni naklon) in ga je potrebno razlikovati od oblikoslovno
skladenjskega pojma 'Satztyp' (stav\~ni tip).

[2] Prim.
tudi
Kemme (1979:7,15d); Weydt/Hentschel (1981:326) ali
Weydt/Harden/Hentschel/Rösler (1983:5,13).
